services:
  apiDemo:
    image: yegudion/5-shea
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/default"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "8001:5432"
    volumes:
      - .:/var/lib/postgresql/data
    restart: always