# Generated by Django 5.0.6 on 2024-05-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_engineer_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_machine_1', models.IntegerField()),
                ('time_machine_2', models.IntegerField()),
            ],
        ),
    ]
